
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: XXXXXXXXXXXX
    server: https://8b5849e5-4b07-4ac1-a166-93fda1db9a93.eu-central-3-gw.linodelke.net:443
  name: lke497779

users:
- name: lke497779-admin
  user:
    as-user-extra: {}
    token: CCCCCCCCCCCCCCC
contexts:
- context:
    cluster: lke497779
    namespace: default
    user: lke497779-admin
  name: lke497779-ctx

current-context: lke497779-ctx
