
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJS1pVVGpoTU8wc2t3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBM01URXhOVEkyTWpkYUZ3MHpOVEEzTURreE5UTXhNamRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM2MG5NYmFLNENTL0FXTFFpd2dQOURvV2JLRjI2cnVYYXYwdjN2dHRieE5nUm9vYnhpekVRTWJlL0MKcnJZd3c0WWhmVUFtNE9JRUxIbm1SenE5NEhYSThVTDRyNWNXT20xK3I0a2JSNDZkdlBnRkt5N1pEbXpqTzljMApYSEh2Ni9oQm9QWjFCMkE2TVlWRWExdDFObE1sUGEwS3lHbFJOQmpsUlNrVVhaaG9Tc09UNlVOUnlaSmpIUHJ1ClczampScnF4b0xtQ0lQTnZRTkd3QnhBR2JoTzRwUVh3SSt1U28xeWRnb1BBY09SQ0lNREdLaXpQT2p0Y0lhSFkKL3Nnd1J5M0UyT1J4WWtENUNoSzljZ0lEcW9acDFPMUZtUThKaDcxbksyY2tLRzhFNHBoUSswR3A3aFprMFMwcQpqb2FlRWlVODNuVG1Iczh0T2QzYkZVWjEyNmFCQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSaXAyaVAvTFlNUWlzakRiRnVzSmFkTzdNQUF6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVNvTmFucUZVWQpoQ204WUtiWWR4MHVOTnFKc3NENUJHVXBWNm9FVVhHNVBtcDUwWUVKZ3FraWljdGlZbVVDbXFOWUlHNkNYWENnCnFnN3hGWTExZUUvTDcvTVdjNndkZDBlaGpMdjh4TE1tUHNFekc3K0JmZkFQTlRERUgxbEhKUFNnUStidFU2T04KVFlkWVVkSGlUNEVQK0xwbDdPMmFxRWJyV0NFdHI3N0dzZmRRczRoZ2c3TitlbEZkNHlYdTR3UDdMT29UYWUrawpqNjRkRkR2NzZhMENGVDlJNU54WDRBbzY0VHZOVkxLbk5CTndWU25rN0RzNFRadVZsTzNOSGtweUZWVks0L0NsCkZyaXpxZGpuK1pBYWszbE9DSTMxUTRQdFJwVjVzYVlpeEhIeVFwVHFCeXR6dFpmTDd5cG9KL25jd05pZitjS1AKQUtRVkdPS0FERkw1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://8b5849e5-4b07-4ac1-a166-93fda1db9a93.eu-central-3-gw.linodelke.net:443
  name: lke497779

users:
- name: lke497779-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkpLYXVVNjBmN2dkUC1BamVYWDROT1VwSDdPSHl4dHpWOEVzenN5dHpYcHMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tc3Bxd2siLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMjZhNjljN2EtM2ViNy00ZjNlLWIyYzUtYjEyMDA2MDY4NTUzIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.fE5pH9zO6cT6Z4G_mNjk2oEHZi-gFj219lTyun1j7JWmjZxcUyiVC2eER_bAOca-ULiJsfKHWlyMws489VRcuPXDW457Zh2pYziTDiaupIDn2AB99IIwGBq3jPzFVs2fln6leDwzziOrwgUvg3rpggiksaKH1ksCNONHzU5teRQlwsfQ4RvIsvrEbEZGgJLu-GpCaD8KZ_V2AiUOamxiY0aHW28tj5sdNPjgTERMU6MRCieV43F-UAxcXia6I3MMjNXrxH7ELZ9_Om3uikwqThV_RlPka77UpzgPSZuOmqc9oz3d-47rkI_XXL_sTbI2TzQ1qBdqcTk4h3NkJfXPlA

contexts:
- context:
    cluster: lke497779
    namespace: default
    user: lke497779-admin
  name: lke497779-ctx

current-context: lke497779-ctx
